name: ocarina-env
dependencies:
- python=3.8
- numpy=1.23
- mpi4py
- anaconda
- pip
- pip:
  - almatasks==1.6.1
  - astropy==5.2.1
  - casadata==2023.1.23
  - casampi==0.5.2
  - casaplotms==1.9.1
  - casaplotserver==1.5.1
  - casashell==6.5.3.28
  - casatasks==6.5.3.28
  - casatestutils==6.5.3.28
  - casatools==6.5.3.28
  - casatablebrowser==0.0.31
  - casalogger==1.0.15
  - casaviewer==1.7.1
  - casafeather==0.0.18
  - scipy==1.10.1
  - python-casacore==3.5.2
