[build-system]
requires = ["setuptools>=65.5.0", "setuptools-scm", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ocarina"
authors = [
    {name = "Miguel Cárcamo", email = "miguel.carcamo@manchester.ac.uk"},
]
maintainers = [
    {name = "Miguel Cárcamo", email = "miguel.carcamo@manchester.ac.uk"},
]
description = "A Python object oriented framework to do polarization calibration"
readme = "README.md"
license = {text = "GNU GPL"}
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
dynamic = ["version", "dependencies"]

[project.urls]
Source = "https://github.com/miguelcarcamov/ocarina"

[tool.setuptools.packages.find]
where = ["src"]
include = ["ocarina*"]
namespaces = false

[tool.setuptools_scm]
write_to = "src/ocarina/_version.py"
